### ISSUE TITLE
Create a single page view

### ISSUE THREAD

**Issue by s-Hale** [s-Hale/BuildTravelCards#10]
If customers click a card, they want to see more. 
Build a single page view for each trip when the card is clicked.

**Comment by joshtom** [comment]
@s-Hale is there a design for this card, Or i will build it from scratch then add the functionality?

**Comment by s-Hale** [comment]
No designs, you can build from scratch :)

**Comment by mjfneto** [comment]
@s-Hale Can I give it a try?

**Comment by s-Hale** [comment]
> @s-Hale Can I give it a try?

Sure :) It's an open activity.

**Comment by mjfneto** [comment]
Cool. Working on it.

**Comment by mjfneto** [comment]
👍 for a routing package? [react-router-dom](https://www.npmjs.com/package/react-router-dom)?

**Comment by mjfneto** [comment]
@s-Hale So that you know it's almost done. @eduqg Routing is working great ✨ Would you mind reviewing my PR? Do you know how we could implement scroll restoration with react-router?
