### ISSUE TITLE
Link styling has reverted to default

### ISSUE THREAD

**Issue by s-Hale** [s-Hale/BuildTravelCards#100]
Yuk! No one wants that blue text and underlines. Can it go back the way it was before - nice, plain text?

Easy issue, no need to claim, just make the PR.

**Comment by vinnyslins** [comment]
Hello, I'll do it!

**Comment by vinnyslins** [comment]
https://github.com/s-Hale/BuildTravelCards/pull/101

**Comment by vinnyslins** [comment]
[https://github.com/s-Hale/BuildTravelCards/pull/101](url)
