### ISSUE TITLE
Width issue

### ISSUE THREAD

**Issue by s-Hale** [s-Hale/BuildTravelCards#116]
The width has gone mad again and there's some kind of console warning.

Test before you push, folks, without testing on the project or any sense of branching it's becoming harder to avoid breaking changes.

**Comment by shravan-balasubramanian** [comment]
Hi. I am interested in this. Can you add a screenshot of the problem

**Comment by chaturanganamal** [comment]
Created a PR. Please review & merge.

**Comment by cindyledev** [comment]
I noticed the Contact.css has a css style of max-width: 420px for the App class. This caused the entire formatting of the cards to change. I will make a PR to fix this problem
