### ISSUE TITLE
Hover effect on Nav

### ISSUE THREAD

**Issue by s-Hale** [s-Hale/BuildTravelCards#12]
It looks terribly plain, and I'm sure some shadow or animation effects would liven things up.

**Comment by mvedataydin** [comment]
I am working on it

**Comment by LisaCee** [comment]
I'll take this one!

**Comment by LisaCee** [comment]
![Picture1](https://user-images.githubusercontent.com/18077352/66350503-58cba380-e910-11e9-89d4-3ee3b71944b7.jpg)

Will this sort of styling work for you?

**Comment by LisaCee** [comment]
I put in PR #66 with my code for this.

**Comment by eKhattak** [comment]
Since the Load More button has Red Hover Effect, to make hovers consistent, I added the same effect to the Navigation bar, You can check my Pull Request.
