### ISSUE TITLE
Add a new trip

### ISSUE THREAD

**Issue by s-Hale** [s-Hale/BuildTravelCards#3]
Following the format given, add a new trip to the page.

**Comment by chetanraj** [comment]
Added New York City

**Comment by jessicavrooyen** [comment]
Added Cape Town ✨

**Comment by amelia678** [comment]
Added Atlanta

**Comment by Apoorva-13** [comment]
Added mauritius #56

**Comment by Apoorva-13** [comment]
Added Mauritius #56

**Comment by wajeehsheikh** [comment]
Hi Hale,

Thank you for giving beginner open-source contributors this opportunity.
I will be adding my manchester trip to your Travelcard interface. 

Thank you
Waj
