### ISSUE TITLE
If (!image)... 

### ISSUE THREAD

**Issue by s-Hale** [s-Hale/BuildTravelCards#51]
Code currently won't compile if users don't include an image with their new trip. Implement a solution that renders either null or a default image in this instance.

**Comment by atrievel** [comment]
Hey @s-Hale, I can take this on if no one else is yet!

**Comment by s-Hale** [comment]
```const cardImage = require(`../../assets/${!image ? 'default-image.jpg' : image}`);```

Fix doesn't work.

Issue still open. Please test the work before submission as it prevents compilation.

**Comment by eduqg** [comment]
Can I try this one?

**Comment by s-Hale** [comment]
@eduqg please do!

I don't think the ! flag works during the whole require thing, so maybe there needs to be an alternative.

**Comment by atrievel** [comment]
@s-Hale This is not what the original requirements were. You mentioned a compilation issue, not a run time issue.

Latest pull request #84 fixes this
