### ISSUE TITLE
"Guests" child should have key prop

### ISSUE THREAD

**Issue by LisaCee** [s-Hale/BuildTravelCards#65]
![Screenshot from 2019-10-07 18-40-25](https://user-images.githubusercontent.com/18077352/66360996-f5eb0400-e931-11e9-8a56-a36d1fb3a046.png)

**Comment by luisFilipePT** [comment]
Hi, Is it up for grabs? If so assign it to me :)

**Comment by LisaCee** [comment]
I don't have permissions to assign,  but it is up for grabs so have at it.

**Comment by luisFilipePT** [comment]
Open PR ☝️ 😄 

BTW Added the `nanoid` package to generate unique keys https://github.com/ai/nanoid#react
With the available data could't find a way to generate unique keys consistently and using the index is a bad practice (and buggy)

Cheers
