### ISSUE TITLE
Max image size

### ISSUE THREAD

**Issue by s-Hale** [s-Hale/BuildTravelCards#82]
People uploading massive images is damaging the layout of the cards.

Implement a solution that keeps the layout fluid and uniform, but prevents this behaviour if people upload massive images.

Some way of shrinking them might be nice too, but I don't know if that can be done by the app.

I might just delete the massive ones, the package size must be getting out of hand now.

**Comment by mcaibad2** [comment]
s-Hale cards width seems equal to me.

**Comment by s-Hale** [comment]
> Travel cards width width seems equal to me using Google Chrome. Are you sure that this has been broken?

Yes, it's 3 or 4 massive images causing the issue.

**Comment by taandsoul** [comment]
@s-Hale are you speaking about this moment? If yes, I found what really caused it and it's not the size of the images.
Can I have this fix?
![Anotação 2019-10-11 231659](https://user-images.githubusercontent.com/44118603/66693289-b7c94980-ec7d-11e9-8bd9-d20dbd1affa6.png)
